name: ocr
description: "Optical Character Recognition with CNN"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_drawing_board: ^0.7.0+2
  image: ^4.2.0
  native_device_orientation: ^2.0.3
  tflite_flutter: ^0.11.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ocr_model.tflite
    - assets/ocr_model_q.tflite
    - assets/quantized_model_xxs.tflite
    - assets/quantized_model_xxs_v2.tflite
